import React,{useEffect,useState} from "react";
import {Routes,Route,Link} from "react-router-dom";
import {Search,MapPin,BriefcaseBusiness,Share2,ExternalLink,Sparkles,ShieldCheck,Plus,RefreshCw,Trash2} from "lucide-react";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000/api";
const categories=["Software Engineering","DevOps","Data","Cybersecurity","QA","AI/ML"];
const industries=["Healthcare","University & Education","Supply Chain","Technology","Finance & Banking","Insurance","Consulting","Retail","Manufacturing","Government","Pharmaceuticals","Energy","Telecommunications","Other"];
function useFetch(path,initial=null){const[data,setData]=useState(initial);const[loading,setLoading]=useState(true);useEffect(()=>{let live=true;setLoading(true);fetch(API+path).then(r=>r.ok?r.json():null).then(d=>{if(live&&d)setData(d)}).catch(()=>{}).finally(()=>live&&setLoading(false));return()=>{live=false}},[path]);return{data,loading}}
function shareJob(j){const url=`${location.origin}/jobs/${j.id}`;if(navigator.share)navigator.share({title:j.title,text:`${j.title} at ${j.company}`,url}).catch(()=>{});else navigator.clipboard?.writeText(url)}
function JobCard({j}){return <article><div className="top"><div className="logo">TI</div><div><h2>{j.title}</h2><Link to={`/companies/${j.company_id}`}><strong>{j.company}</strong></Link></div><button onClick={()=>shareJob(j)} title="Share job"><Share2 size={18}/></button></div><div className="meta"><span><MapPin size={15}/>{j.location||"USA"}</span><span><BriefcaseBusiness size={15}/>{j.location_type}</span><span>{j.experience_level}</span></div><p className="posted">Published {j.posted_at?new Date(j.posted_at).toLocaleDateString():"—"} · Currently open on source</p><h3><Sparkles size={16}/> Skills mentioned in this job</h3><div className="skills">{(j.skills||[]).filter(Boolean).map(s=><span key={s}>{s}</span>)}</div><div className="actions"><Link to={`/jobs/${j.id}`}>View Details</Link><a className="apply" href={j.apply_url} target="_blank" rel="noreferrer">Apply <ExternalLink size={15}/></a></div></article>}
function Home(){const[q,setQ]=useState(""),[level,setLevel]=useState(""),[category,setCategory]=useState(""),[industry,setIndustry]=useState("");const{data,loading}=useFetch(`/jobs?q=${encodeURIComponent(q)}&level=${level}&category=${encodeURIComponent(category)}&industry=${encodeURIComponent(industry)}`,{jobs:[]});const jobs=data?.jobs||[];return <><nav><div className="brand"><span>TI</span><b>Talent Inspirations</b></div><div><Link to="/">Jobs</Link> <Link to="/industries">Industries</Link> <Link to="/admin">Admin</Link></div></nav><header><div className="eyebrow">🇺🇸 USA CAREERS ONLY</div><h1>Current published <em>opportunities.</em></h1><p>Only jobs currently published/open on employer career sources, limited to USA and the latest 30 days.</p><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search job title, skill, company..."/></div></header><main><div className="toolbar"><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All Experience</option><option value="fresher">Fresher</option><option value="experienced">Experienced</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All Job Categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select value={industry} onChange={e=>setIndustry(e.target.value)}><option value="">All Industries</option>{industries.map(x=><option key={x}>{x}</option>)}</select><span>{loading?"Loading…":`${jobs.length} current USA jobs · published in last 30 days`}</span></div><section className="grid">{jobs.map(j=><JobCard key={j.id} j={j}/>)}</section>{!loading&&!jobs.length&&<div className="empty">No currently published/open USA jobs match these filters.</div>}</main></>}
function JobPage(){const id=location.pathname.split("/").pop();const{data,loading}=useFetch(`/jobs/${id}`,null);const job=data?.job;const related=useFetch(job?`/jobs/${id}/related`:"/jobs/0",{jobs:[]}).data?.jobs||[];if(loading)return <main className="detail">Loading job…</main>;if(!job)return <main className="detail"><Link to="/">← Jobs</Link><h1>Job unavailable</h1><p>This job is no longer in the public current/open 30-day index.</p></main>;return <main className="detail"><Link to="/">← All USA Jobs</Link><div className="detailhead"><div><div className="eyebrow">CURRENTLY PUBLISHED / OPEN</div><h1>{job.title}</h1><Link to={`/companies/${job.company_id}`}><h2>{job.company}</h2></Link><p>{job.location} · {job.location_type} · {job.experience_level}</p></div><button onClick={()=>shareJob(job)}><Share2/> Share</button></div><div className="panel"><p>Published: {new Date(job.posted_at).toLocaleString()}</p><p>Public index expiry: {new Date(job.expires_at).toLocaleString()}</p><h2>Skills mentioned in this job</h2><div className="skills">{(job.skills||[]).filter(Boolean).map(s=><span key={s}>{s}</span>)}</div><h2>Job description</h2><div className="description">{String(job.description||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim()}</div><div className="actions"><a className="apply" href={job.apply_url} target="_blank" rel="noreferrer">Apply on employer site <ExternalLink size={16}/></a></div></div>{related.length>0&&<><h2>Related current jobs</h2><div className="grid">{related.map(j=><JobCard key={j.id} j={j}/>)}</div></>}</main>}
function CompanyPage(){const id=location.pathname.split("/").pop();const{data,loading}=useFetch(`/companies/${id}`,null);const{data:jobsData}=useFetch(`/companies/${id}/jobs`,{jobs:[]});if(loading)return <main className="detail">Loading company…</main>;const c=data?.company;if(!c)return <main className="detail"><Link to="/">← Jobs</Link><h1>Company not found</h1></main>;return <main><Link to="/">← Jobs</Link><div className="companyHero"><div className="logo">TI</div><div><div className="eyebrow">CURRENT HIRING</div><h1>{c.name}</h1><p>{c.industry} · {c.current_hiring} currently published/open USA jobs</p></div><a className="apply" href={c.career_url} target="_blank" rel="noreferrer">Career site <ExternalLink size={15}/></a></div><h2>Current hiring</h2><section className="grid">{(jobsData?.jobs||[]).map(j=><JobCard key={j.id} j={{...j,company:c.name}}/>)}</section>{!(jobsData?.jobs||[]).length&&<div className="empty">No currently published/open USA jobs in the public 30-day index.</div>}</main>}
function Industries(){const{data}=useFetch("/industries",{industries:[]});return <main><Link to="/">← Jobs</Link><h1>Industries</h1><section className="grid">{(data?.industries||[]).map(x=><Link className="panel" key={x.industry} to={`/?industry=${encodeURIComponent(x.industry)}`}><h2>{x.industry}</h2><p>{x.current_jobs} current USA jobs</p></Link>)}</section></main>}
function Admin(){const[token,setToken]=useState(localStorage.getItem("ti_token")||""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[companyName,setCompany]=useState(""),[careerUrl,setUrl]=useState(""),[industry,setIndustry]=useState("Other"),[sources,setSources]=useState([]),[manualJobs,setManualJobs]=useState([]),[editing,setEditing]=useState(null),[msg,setMsg]=useState(""),[manual,setManual]=useState({companyId:"",companyName:"",careerUrl:"",title:"",description:"",location:"",locationType:"unknown",experienceLevel:"other",category:"Software Engineering",employmentType:"",skills:"",applyUrl:"",postedAt:""});
 const load=()=>token&&Promise.all([fetch(API+"/admin/sources",{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()),fetch(API+"/admin/jobs",{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json())]).then(([s,j])=>{setSources(s.sources||[]);setManualJobs(j.jobs||[])}).catch(()=>{});useEffect(load,[token]);
 const login=async e=>{e.preventDefault();const r=await fetch(API+"/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(d.token){localStorage.setItem("ti_token",d.token);setToken(d.token)}else setMsg(d.error||"Login failed")};
 const add=async e=>{e.preventDefault();const r=await fetch(API+"/admin/sources",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({companyName,careerUrl,industry,autoSync:true})});const d=await r.json();setMsg(d.message||d.error);if(r.ok){setCompany("");setUrl("");load()}};
 const addManual=async e=>{e.preventDefault();const body={...manual,companyId:manual.companyId||undefined,skills:manual.skills.split(",").map(x=>x.trim()).filter(Boolean)};const r=await fetch(API+(editing?"/admin/jobs/"+editing:"/admin/jobs"),{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const d=await r.json();setMsg(d.message||d.error);if(r.ok){setManual({...manual,title:"",description:"",location:"",skills:"",applyUrl:"",postedAt:""});setEditing(null);load()}};
 const setM=(k,v)=>setManual(x=>({...x,[k]:v}));
 const sync=async id=>{const r=await fetch(API+"/admin/sources/"+id+"/sync",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const d=await r.json();setMsg(d.message||`Sync complete: ${d.imported??0} imported`);load()};
 const remove=async id=>{if(!confirm("Delete this career source?"))return;const r=await fetch(API+"/admin/sources/"+id,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});const d=await r.json();setMsg(d.message||d.error||"Source removed");load()};
 const removeManual=async id=>{if(!confirm("Remove this manual job from public listing?"))return;const r=await fetch(API+"/admin/jobs/"+id,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});const d=await r.json();setMsg(d.message||d.error);load()};
 const editManual=j=>{setEditing(j.id);setManual({companyId:j.company_id,companyName:"",careerUrl:"",title:j.title,description:j.description,location:j.location||"",locationType:j.location_type||"unknown",experienceLevel:j.experience_level||"other",category:j.category||"Software Engineering",employmentType:j.employment_type||"",skills:(j.skills||[]).join(", "),applyUrl:j.apply_url,postedAt:j.posted_at?new Date(j.posted_at).toISOString().slice(0,10):""})};
 if(!token)return <main className="admin"><Link to="/">← Website</Link><div className="panel"><ShieldCheck size={30}/><h1>Admin Login</h1><form onSubmit={login}><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="apply">Login</button></form><p>{msg}</p></div></main>;
 return <main className="admin"><div className="adminhead"><div><Link to="/">← Website</Link><h1>Career Sources</h1></div><button onClick={()=>{localStorage.removeItem("ti_token");setToken("")}}>Logout</button></div>
 <div className="panel"><h2><Plus/> Add Career Page</h2><p>Automatic import source. The system will sync currently published/open USA jobs.</p><form onSubmit={add}><input value={companyName} onChange={e=>setCompany(e.target.value)} placeholder="Company name" required/><input value={careerUrl} onChange={e=>setUrl(e.target.value)} placeholder="https://company.com/careers" type="url" required/><select value={industry} onChange={e=>setIndustry(e.target.value)}>{industries.map(x=><option key={x}>{x}</option>)}</select><button className="apply">Add Source</button></form></div>
 <div className="panel"><h2><Plus/> {editing?"Edit Manual Job":"Custom Job Add"}</h2><p>Jis company/source ka automatic importer available nahi hai, direct career page se details copy karke yahan manually publish kar sakte ho.</p><form onSubmit={addManual}>
 <select value={manual.companyId} onChange={e=>setM("companyId",e.target.value)}><option value="">New/existing company by name</option>{sources.map(s=><option key={s.company_id} value={s.company_id}>{s.company} — {s.industry}</option>)}</select>
 <input value={manual.companyName} onChange={e=>setM("companyName",e.target.value)} placeholder="Company name (if not listed)" />
 <input value={manual.careerUrl} onChange={e=>setM("careerUrl",e.target.value)} placeholder="Company career page URL" type="url"/>
 <input value={manual.title} onChange={e=>setM("title",e.target.value)} placeholder="Job title" required/>
 <textarea value={manual.description} onChange={e=>setM("description",e.target.value)} placeholder="Paste complete job description" rows="9" required/>
 <input value={manual.location} onChange={e=>setM("location",e.target.value)} placeholder="USA location e.g. Dallas, TX / Remote - United States" required/>
 <div className="formrow"><select value={manual.locationType} onChange={e=>setM("locationType",e.target.value)}><option value="unknown">Work mode unknown</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">Onsite</option></select><select value={manual.experienceLevel} onChange={e=>setM("experienceLevel",e.target.value)}><option value="other">Experience — Other</option><option value="fresher">Fresher</option><option value="experienced">Experienced</option></select><select value={manual.category} onChange={e=>setM("category",e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></div>
 <input value={manual.employmentType} onChange={e=>setM("employmentType",e.target.value)} placeholder="Employment type e.g. Full-time"/>
 <input value={manual.skills} onChange={e=>setM("skills",e.target.value)} placeholder="Skills, comma separated: Java, Spring Boot, AWS, SQL"/>
 <input value={manual.applyUrl} onChange={e=>setM("applyUrl",e.target.value)} placeholder="Original employer Apply URL" type="url" required/>
 <label>Published date <input value={manual.postedAt} onChange={e=>setM("postedAt",e.target.value)} type="date"/></label>
 <button className="apply">{editing?"Update Custom USA Job":"Publish Custom USA Job"}</button></form></div>
 <p>{msg}</p>
 <div className="panel"><h2>Manual Jobs ({manualJobs.length})</h2><p>Custom jobs added directly from employer career pages.</p>{manualJobs.length===0?<small>No manual jobs yet.</small>:manualJobs.map(j=><div className="source" key={j.id}><div><b>{j.title}</b><small>{j.company} · {j.location} · {j.experience_level}<br/>Published {j.posted_at?new Date(j.posted_at).toLocaleDateString():"—"} · {j.is_active?"Public":"Removed"}</small></div><span><button onClick={()=>editManual(j)}>Edit</button> <button onClick={()=>removeManual(j.id)}><Trash2 size={15}/></button></span></div>)}</div><div className="panel"><h2>Automatic Sources</h2>{sources.map(s=><div className="source" key={s.id}><div><b>{s.company}</b><small>{s.ats_type} · {s.industry}<br/>Current USA jobs: {s.current_jobs||0}<br/>{s.source_url}</small></div><span><button onClick={()=>sync(s.id)}><RefreshCw size={15}/></button> <button onClick={()=>remove(s.id)}><Trash2 size={15}/></button></span></div>)}</div></main>}

export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/jobs/:id" element={<JobPage/>}/><Route path="/companies/:id" element={<CompanyPage/>}/><Route path="/industries" element={<Industries/>}/><Route path="/admin" element={<Admin/>}/></Routes>}
