const STOP=new Set("a an the and or of to for with in on by from at as is are be this that we you our their your into about using use used work working role job jobs team teams experience years year".split(" "));
const ROLE_MAP={
 "Software Engineering":["software engineer","software developer","full stack","backend","frontend","java","spring","react","angular","node"],
 DevOps:["devops","sre","site reliability","kubernetes","terraform","docker","jenkins","aws","azure","gcp","linux"],
 Data:["data analyst","business analyst","data engineer","sql","tableau","power bi","snowflake","databricks"],
 Cybersecurity:["cybersecurity","security engineer","iam","soc","infosec","penetration","vulnerability"],
 QA:["qa","quality assurance","sdet","selenium","automation testing","test engineer"],
 "AI/ML":["machine learning","artificial intelligence","ai engineer","ml engineer","pytorch","tensorflow","llm"]
};
const COMMON_SKILLS=["Java","Spring Boot","JavaScript","TypeScript","React","Angular","Python","SQL","MySQL","PostgreSQL","MongoDB","AWS","Azure","GCP","Docker","Kubernetes","Terraform","Jenkins","GitHub Actions","Linux","Node.js","C#","C++","Go","Kafka","Power BI","Tableau","Excel","Selenium","Git","REST","GraphQL","PHP","Laravel","Snowflake","Databricks","Spark","Airflow","TensorFlow","PyTorch","R","Scala","Ruby","Rust","Swift","Oracle","SAP","Salesforce","ServiceNow"];
function extractSkills(text=""){const s=String(text);return COMMON_SKILLS.filter(x=>new RegExp("(^|[^A-Za-z0-9+#.])"+x.replace(/[.*+?^{}()|[\]\\]/g,"\\$&")+"([^A-Za-z0-9+#.]|$)","i").test(s));}
function roleFor(job){const s=(job.title+" "+job.description+" "+job.category).toLowerCase();for(const [role,terms] of Object.entries(ROLE_MAP)){if(terms.some(t=>s.includes(t)))return role}return job.category||"Software Engineering";}
function requiredExperience(text=""){const m=String(text).match(/(\d+)(?:\s*[-–]\s*(\d+))?\+?\s*years?[^.]{0,80}/i);if(m)return m[2]?m[1]+"-"+m[2]+" years of relevant experience":m[1]+"+ years of relevant experience";if(/senior|sr\.?|lead|principal|staff/i.test(text))return "Senior-level professional experience is indicated by the job description.";if(/junior|entry|new grad|graduate|intern/i.test(text))return "Entry-level or early-career experience is indicated by the job description.";return "Relevant professional experience aligned with the responsibilities in the job description.";}
function twoPointSummary(job,matched,missing){const desc=String(job.description||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();const sentence=desc.split(/(?<=[.!?])\s+/).filter(x=>x.length>35)[0]||"Deliver the responsibilities described for this role using the required technical and collaboration skills.";return [`Role focus: ${sentence.slice(0,240)}`,`ATS focus: ${matched.slice(0,8).join(", ")||"Core role skills"}${missing.length?"; strengthen "+missing.slice(0,5).join(", "):"; strong keyword alignment"}.`];}
function tailorResume(user,job,matched){const master=String(user.master_cv_text||"").trim();const name=user.name||"Candidate";const role=job.title;const skills=matched.length?matched.join(", "):"the role-specific skills listed in the JD";const base=master||"Candidate professional profile.\nAdd the candidate's verified education, experience and project history here.";return `TARGETED RESUME — ${role}\n\n${name}\n\nPROFESSIONAL SUMMARY\nResults-oriented professional targeting ${role}, with experience and skills aligned to ${skills}. This version is tailored from the candidate master CV and the employer job description.\n\nCORE SKILLS\n${skills}\n\nMASTER CV CONTENT\n${base}\n\nTARGET ROLE KEYWORDS\n${skills}`;}
function coverLetter(user,job,matched){const name=user.name||"Candidate";const company=job.company||"your organization";return `Dear Hiring Team at ${company},\n\nI am writing to apply for the ${job.title} position. My background and the skills in my master CV align with the requirements highlighted in this opportunity, particularly ${matched.slice(0,6).join(", ")||"the role's core responsibilities"}.\n\nI would welcome the opportunity to contribute to the team and discuss how my experience can support the objectives described in the job posting.\n\nThank you for your consideration.\n\nSincerely,\n${name}`;}
export function analyzeJob(job,user={}){const jd=[job.title,job.description,job.location,job.category].join("\n");const jdSkills=extractSkills(jd);const profileSkills=[...new Set([...(Array.isArray(user.profile_skills)?user.profile_skills:[]),...extractSkills(user.master_cv_text||"")])];const matched=jdSkills.filter(s=>profileSkills.some(p=>p.toLowerCase()===s.toLowerCase()));const missing=jdSkills.filter(s=>!matched.includes(s));const score=jdSkills.length?Math.min(100,Math.round((matched.length/jdSkills.length)*100)):0;const summary=twoPointSummary(job,matched,missing);return {atsScore:score,atsSkills:jdSkills,matchedSkills:matched,missingSkills:missing,summaryPoints:summary,experienceSummary:requiredExperience(jd),role:roleFor(job),tailoredResume:tailorResume(user,job,matched),coverLetter:coverLetter(user,job,matched)};}
export async function ensureJobIntelligence(pool,jobId,userId){const [[job]]=await pool.query(`SELECT j.*,c.name company,c.industry FROM jobs j JOIN companies c ON c.id=j.company_id WHERE j.id=? LIMIT 1`,[jobId]);if(!job)return null;const [[user]]=await pool.query("SELECT id,name,profile_skills_json,master_cv_text FROM users WHERE id=? LIMIT 1",[userId]);let profile=[];try{profile=JSON.parse(user?.profile_skills_json||"[]")}catch{}const a=analyzeJob({...job,profile_skills:profile},{...user,profile_skills:profile});await pool.query(`INSERT INTO job_intelligence(job_id,ats_score,ats_skills_json,matched_skills_json,missing_skills_json,summary_points_json,experience_summary,tailored_resume,cover_letter) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE ats_score=VALUES(ats_score),ats_skills_json=VALUES(ats_skills_json),matched_skills_json=VALUES(matched_skills_json),missing_skills_json=VALUES(missing_skills_json),summary_points_json=VALUES(summary_points_json),experience_summary=VALUES(experience_summary),tailored_resume=VALUES(tailored_resume),cover_letter=VALUES(cover_letter),updated_at=NOW()`,[jobId,a.atsScore,JSON.stringify(a.atsSkills),JSON.stringify(a.matchedSkills),JSON.stringify(a.missingSkills),JSON.stringify(a.summaryPoints),a.experienceSummary,a.tailoredResume,a.coverLetter]);return {job,...a};}
export async function buildTodayBuckets(pool,userId){const [[user]]=await pool.query("SELECT * FROM users WHERE id=? LIMIT 1",[userId]);if(!user)return [];let profile=[];try{profile=JSON.parse(user.profile_skills_json||"[]")}catch{}const [jobs]=await pool.query(`SELECT j.id,j.company_id,c.name company,c.industry,j.title,j.description,j.location,j.country,j.category,j.experience_level,j.skills_json,j.apply_url,j.posted_at,j.first_seen_at FROM jobs j JOIN companies c ON c.id=j.company_id WHERE j.is_active=1 AND j.country=? AND j.expires_at>NOW() AND COALESCE(j.posted_at,j.first_seen_at)>=CURDATE() ORDER BY COALESCE(j.posted_at,j.first_seen_at) DESC,j.id DESC LIMIT 500`,[user.country||"USA"]);const buckets=new Map();for(const job of jobs){let skills=[];try{skills=JSON.parse(job.skills_json||"[]")}catch{}const text=(job.title+" "+job.description+" "+skills.join(" ")).toLowerCase();const profileHit=profile.length?profile.some(s=>text.includes(String(s).toLowerCase())):true;const key=roleFor(job);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push({...job,skills,profileMatch:profileHit});}return [...buckets.entries()].map(([name,items])=>({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),count:items.length,jobs:items}));}
